/// The models themselves are generated by `json_serializable`; what cannot be
/// generated is the handful of conversions this app's wire format needs, and
/// those live here so every model spells them the same way.
library;

import 'package:json_annotation/json_annotation.dart';

/// Dates arrive as ISO-8601 UTC and are held in local time.
class LocalDateTime implements JsonConverter<DateTime, String> {
  const LocalDateTime();

  @override
  DateTime fromJson(String json) => DateTime.parse(json).toLocal();

  @override
  String toJson(DateTime object) => object.toUtc().toIso8601String();
}

class LocalDateTimeOrNull implements JsonConverter<DateTime?, String?> {
  const LocalDateTimeOrNull();

  @override
  DateTime? fromJson(String? json) {
    return json == null ? null : DateTime.parse(json).toLocal();
  }

  @override
  String? toJson(DateTime? object) => object?.toUtc().toIso8601String();
}
