/// The plumbing that sits between the wire format and the domain models.
///
/// The models themselves are generated by `json_serializable`; what cannot be
/// generated is the handful of conversions this app's wire format needs, and
/// those live here so every model spells them the same way.
library;

import 'package:json_annotation/json_annotation.dart';

typedef JsonType = Map<String, dynamic>;
typedef ParseFn<T> = T Function(JsonType);

/// A domain enum with a stable over-the-wire spelling.
///
/// The API sends `in_progress` where the Dart constant is `inProgress`, so
/// `values.byName(...)` throws; every such enum carries its wire string and
/// looks itself up by it instead.
abstract interface class WireEnum {
  String get wire;
}

extension WireValues<T extends WireEnum> on List<T> {
  T? tryByWire(String? wire) {
    for (final value in this) {
      if (value.wire == wire) return value;
    }
    return null;
  }

  /// [label] names the enum in the failure, so a bad payload says which field
  /// it came from rather than just that some enum did not match.
  T byWire(String wire, {required String label}) =>
      tryByWire(wire) ?? (throw FormatException('Unknown $label: $wire'));
}

/// Bridges a [WireEnum] into the generated `fromJson`.
///
/// Encoding is the same for every wire enum, so subclasses supply only the
/// decode, and they do it by delegating to their own `fromWire` — that keeps
/// one lookup and one failure message per enum rather than a second copy here.
abstract class WireConverter<T extends WireEnum>
    implements JsonConverter<T, String> {
  const WireConverter();

  @override
  String toJson(T object) => object.wire;
}

/// Dates arrive as ISO-8601 UTC and are held in local time.
///
/// `DateTime.parse` on its own leaves them in UTC, and Dart's `DateTime`
/// equality counts `isUtc` — so dropping the `toLocal()` would quietly change
/// every date comparison and every date the UI renders.
class LocalDateTime implements JsonConverter<DateTime, String> {
  const LocalDateTime();

  @override
  DateTime fromJson(String json) => DateTime.parse(json).toLocal();

  @override
  String toJson(DateTime object) => object.toUtc().toIso8601String();
}

class LocalDateTimeOrNull implements JsonConverter<DateTime?, String?> {
  const LocalDateTimeOrNull();

  @override
  DateTime? fromJson(String? json) =>
      json == null ? null : DateTime.parse(json).toLocal();

  @override
  String? toJson(DateTime? object) => object?.toUtc().toIso8601String();
}
