[test]
coverageDir = "coverage"
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "./src/common/constants/*",
  "./src/common/helpers/*",
  "./src/config/**",
  "./src/modules/db/**",
  "./src/modules/*/*.schema.ts",
]
